# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: Import Stories
    modelClass: Unisa\Storycore\Models\StoriesImport
    list: $/unisa/storycore/models/storycore/columns.yaml

export:
    title: Export Stories
    modelClass: Unisa\Storycore\Models\StoriesExport
    list: $/unisa/storycore/models/storycore/columns.yaml
    #useList: true