# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Export Controller

# Model Form Field configuration
form: $/unisa/storycore/models/exportcontroller/fields.yaml

# Model Class name
modelClass: Unisa\Storycore\Models\ExportController

# Default redirect location
defaultRedirect: unisa/storycore/exportcontroller

# Create page
create:
    title: Create Export Controller
    redirect: unisa/storycore/exportcontroller/update/:id
    redirectClose: unisa/storycore/exportcontroller

# Update page
update:
    title: Edit Export Controller
    redirect: unisa/storycore/exportcontroller
    redirectClose: unisa/storycore/exportcontroller

# Preview page
preview:
    title: Preview Export Controller