plugin:
    name: 'unisa.pages::lang.plugin.name'
    description: 'unisa.pages::lang.plugin.description'
    author: Unisa
    icon: oc-icon-files-o
    homepage: ''
permissions:
    pages.manage_pages:
        tab: 'unisa.pages::lang.pages.manage_pages'
        label: 'unisa.pages::lang.pages.manage_pages'
navigation:
    pages:
        label: 'unisa.pages::lang.plugin.name'
        url: unisa/pages/pages
        icon: icon-files-o
        sideMenu:
            manage_pages:
                label: 'unisa.pages::lang.pages.manage_pages'
                url: unisa/pages/pages
                icon: icon-sitemap
