title: Ltiobject
modelClass: Unisa\Ltiobject\Models\Ltiobject
list: $/unisa/ltiobject/models/ltiobject/columns.yaml
recordUrl: 'unisa/ltiobject/ltiobject/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
