name: Ltiobject
modelClass: Unisa\Ltiobject\Models\Ltiobject
form: $/unisa/ltiobject/models/ltiobject/fields.yaml
defaultRedirect: unisa/ltiobject/ltiobject
create:
    redirect: 'unisa/ltiobject/ltiobject/update/:id'
    redirectClose: unisa/ltiobject/ltiobject
update:
    redirect: unisa/ltiobject/ltiobject
    redirectClose: unisa/ltiobject/ltiobject
preview: {  }
