# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Import Controller

# Model Form Field configuration
form: $/unisa/storycore/models/importcontroller/fields.yaml

# Model Class name
modelClass: Unisa\Storycore\Models\ImportController

# Default redirect location
defaultRedirect: unisa/storycore/importcontroller

# Create page
create:
    title: Create Import Controller
    redirect: unisa/storycore/importcontroller/update/:id
    redirectClose: unisa/storycore/importcontroller

# Update page
update:
    title: Edit Import Controller
    redirect: unisa/storycore/importcontroller
    redirectClose: unisa/storycore/importcontroller

# Preview page
preview:
    title: Preview Import Controller