title: Taxonomies
modelClass: Unisa\Taxonomy\Models\Taxonomy
list: $/unisa/taxonomy/models/taxonomy/columns.yaml
recordUrl: 'unisa/taxonomy/taxonomies/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
