plugin:
    name: 'unisa.assets::lang.plugin.name'
    description: 'unisa.assets::lang.plugin.description'
    author: Unisa
    icon: oc-icon-briefcase
    homepage: ''
permissions:
    assets.manage_assets:
        tab: 'unisa.assets::lang.assets.manage_assets'
        label: 'unisa.assets::lang.assets.manage_assets'
navigation:
    assets:
        label: 'unisa.assets::lang.plugin.name'
        url: unisa/assets/assets
        icon: icon-briefcase
        sideMenu:
            manage_assets:
                label: 'unisa.assets::lang.assets.manage_assets'
                url: unisa/assets/assets
                icon: icon-sitemap
