plugin:
    name: 'unisa.ltiobject::lang.plugin.name'
    description: 'unisa.ltiobject::lang.plugin.description'
    author: Unisa
    icon: oc-icon-anchor
    homepage: ''
permissions:
    lti.manage_ltiobject:
        tab: 'unisa.ltiobject::lang.LTI.lti_object'
        label: 'unisa.ltiobject::lang.LTI.lti_object'
navigation:
    lti_object:
        label: 'unisa.ltiobject::lang.LTI.lti_object'
        url: unisa/ltiobject/ltiobject
        icon: icon-anchor
        sideMenu:
            manage_lti_object:
                label: 'unisa.ltiobject::lang.LTI.mange_lti_object'
                url: unisa/ltiobject/ltiobject
                icon: icon-sitemap
