title: Storymenus
modelClass: Unisa\Storymenu\Models\Storymenu
list: $/unisa/storymenu/models/storymenu/columns.yaml
recordUrl: 'unisa/storymenu/storymenus/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '30'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
